# -*- python -*-
from lsst.sconsUtils import tests, env

for fileName in Glob("*.cc"):
    env.Program(fileName, LIBS=env.getLibs("main"))

control = tests.Control(env, verbose = True)

control.run("*.cc")
