# -*- python -*-
Import("env")

import glob
import lsst.sconsUtils.tests

for fileName in glob.glob("*.cc"):
    env.Program(fileName, LIBS=env.getLibs("main"))

tests = lsst.sconsUtils.tests.Control(env, verbose = True)

tests.run("*.cc")
